### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Succubussix** [andremm/lua-parser#14]
I have questions.. and the ast is mind blowing to loop 😂

in string we have this

[09:01 ob ]$ ob
{ `Set{ { `Id "main" }, { `Function{ {  }, { `Set{ { `Id "select" }, { `Call{ `Index{ `Id "gg", `String "choice" }, `Table{ `String "test1", `String "test2" } } } }, `If{ `Op{ "eq", `Id "select", `Number "1" }, { `Call{ `Index{ `Id "test", `String "show" } } } }, `If{ `Op{ "eq", `Id "select", `Number "2" }, { `Call{ `Index{ `Id "test", `String "show2" } } } } } } } }, `Set{ { `Id "a" }, { `Number "1" } }, `Set{ { `Id "b" }, { `String "3(£+£+£+£+" } }, `Set{ { `Id "test" }, { `Table{ `Pair{ `String "show", `Function{ {  }, { `Call{ `Index{ `Id "gg", `String "alert" }, `String "find me" } } } }, `Pair{ `String "show2", `Function{ {  }, { `Call{ `Index{ `Id "gg", `String "alert" }, `String "yay me" } } } } } } }, `Call{ `Id "main" } }

and. i have this as table
``
{ { { { "main",
        pos = 10,
        tag = "Id"
      } }, { { {}, { { { { "select",
                pos = 21,
                tag = "Id"
              },
              pos = 21,
              tag = "VarList"
            }, { { { { "gg",
                    pos = 30,
                    tag = "Id"
                  }, { "choice",
                    pos = 33,
                    tag = "String"
                  },
                  pos = 30,
                  tag = "Index"
                }, { { "test1",
                    pos = 51,
                    tag = "String"
                  }, { "test2",
                    pos = 69,
                    tag = "String"
                  },
                  pos = 40,
                  tag = "Table"
                },
                pos = 30,
                tag = "Call"
              },
              pos = 30,
              tag = "ExpList"
            },
            pos = 21,
            tag = "Set"
          }, { { "eq", { "select",
                pos = 91,
                tag = "Id"
              }, { 1,
                pos = 101,
                tag = "Number"
              },
              pos = 91,
              tag = "Op"
            }, { { { { "test",
                    pos = 108,
                    tag = "Id"
                  }, { "show",
                    pos = 113,
                    tag = "String"
                  },
                  pos = 108,
                  tag = "Index"
                },
                pos = 108,
                tag = "Call"
              },
              pos = 108,
              tag = "Block"
            },
            pos = 88,
            tag = "If"
          }, { { "eq", { "select",
                pos = 131,
                tag = "Id"
              }, { 2,
                pos = 141,
                tag = "Number"
              },
              pos = 131,
              tag = "Op"
            }, { { { { "test",
                    pos = 148,
                    tag = "Id"
                  }, { "show2",
                    pos = 153,
                    tag = "String"
                  },
                  pos = 148,
                  tag = "Index"
                },
                pos = 148,
                tag = "Call"
              },
              pos = 148,
              tag = "Block"
            },
            pos = 128,
            tag = "If"
          },
          pos = 21,
          tag = "Block"
        },
        pos = 14,
        tag = "Function"
      } },
    pos = 1,
    tag = "Set"
  }, { { { "a",
        pos = 177,
        tag = "Id"
      },
      pos = 177,
      tag = "VarList"
    }, { { 1,
        pos = 181,
        tag = "Number"
      },
      pos = 181,
      tag = "ExpList"
    },
    pos = 177,
    tag = "Set"
  }, { { { "b",
        pos = 187,
        tag = "Id"
      },
      pos = 187,
      tag = "VarList"
    }, { { "3(£+£+£+£+",
        pos = 191,
        tag = "String"
      },
      pos = 191,
      tag = "ExpList"
    },
    pos = 187,
    tag = "Set"
  }, { { { "test",
        pos = 212,
        tag = "Id"
      },
      pos = 212,
      tag = "VarList"
    }, { { { { "show",
            pos = 229,
            tag = "String"
          }, { {}, { { { { "gg",
                    pos = 259,
                    tag = "Id"
                  }, { "alert",
                    pos = 262,
                    tag = "String"
                  },
                  pos = 259,
                  tag = "Index"
                }, { "find me",
                  pos = 268,
                  tag = "String"
                },
                pos = 259,
                tag = "Call"
              },
              pos = 259,
              tag = "Block"
            },
            pos = 244,
            tag = "Function"
          },
          pos = 229,
          tag = "Pair"
        }, { { "show2",
            pos = 300,
            tag = "String"
          }, { {}, { { { { "gg",
                    pos = 331,
                    tag = "Id"
                  }, { "alert",
                    pos = 334,
                    tag = "String"
                  },
                  pos = 331,
                  tag = "Index"
                }, { "yay me",
                  pos = 340,
                  tag = "String"
                },
                pos = 331,
                tag = "Call"
              },
              pos = 331,
              tag = "Block"
            },
            pos = 316,
            tag = "Function"
          },
          pos = 300,
          tag = "Pair"
        },
        pos = 219,
        tag = "Table"
      },
      pos = 219,
      tag = "ExpList"
    },
    pos = 212,
    tag = "Set"
  }, { { "main",
      pos = 372,
      tag = "Id"
    },
    pos = 372,
    tag = "Call"
  },
  pos = 1,
  tag = "Block"
}

``

how can i loop in all of this?
hmm I want to get all
functions name
variable names

the script looks like this

``
function main()
    select = gg.choice({
         "test1",
         "test2"
    })
    if select == 1 then test.show() end
    if select == 2 then test.show2() end
    end
    a = 1
    b = "3(£+£+£+£+"
    test = {
        show = function()
            gg.alert("find me")
        end,
        show2 = function()
            gg.alert("yay me")
        end
    }
    main()
``

**Comment by Succubussix** [comment]
never mind I already know it thanks. 
``
Script ended:
table(3e537ac): {
	[Functions] = table(a974c75): {
	[1] = test
	[2] = show
	[3] = show2
	[4] = main
}
}
``

but using this https://github.com/efrederickson/LuaAssemblyTools

... please comment if you can give me snippets . to list all functions.. variables. ..using this

**Comment by andremm** [comment]
>... please comment if you can give me snippets . to list all functions.. variables. ..using this

You have to traverse the AST, like what is being done by the `pp` module to print it.
