### ISSUE TITLE
parsing error are not properly reported

### ISSUE THREAD

**Issue by ImpleLee** [andremm/lua-parser#18]
# Steps to reproduce
0. create an empty directory in `/tmp` and `cd` into it.
1. `pip install hererocks`
2. `hererocks . -r^ --lua=5.3`
3. `./bin/luarocks install lua-parser`
4. copy the code example in `README` as `parse.lua`:
```
local parser = require "lua-parser.parser"
local pp = require "lua-parser.pp"

if #arg ~= 1 then
    print("Usage: parse.lua <string>")
    os.exit(1)
end

local ast, error_msg = parser.parse(arg[1], "example.lua")
if not ast then
    print(error_msg)
    os.exit(1)
end

pp.print(ast)
os.exit(0)
```
5. `./bin/lua parse.lua "for i=1, 10 do print(i)"`

# Expected behavior
```
example.lua:1:24: syntax error, expected 'end' to close the for loop
```

# Actual behavior
```
./bin/lua: ./share/lua/5.3/lua-parser/parser.lua:478: attempt to get length of a number value (local 'sfail')
stack traceback:
	./share/lua/5.3/lua-parser/parser.lua:478: in function 'lua-parser.parser.parse'
	parse.lua:9: in main chunk
	[C]: in ?
```

**Comment by ImpleLee** [comment]
# System Information
```
$ uname -srvmo
Linux 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 GNU/Linux
```

**Comment by ImpleLee** [comment]
# Package Information
```
$ ./bin/luarocks list

Rocks installed for Lua 5.3
---------------------------

lpeglabel
   1.6.0-1 (installed) - ./lib/luarocks/rocks-5.3

lua-parser
   1.0.1-1 (installed) - ./lib/luarocks/rocks-5.3

```

**Comment by ImpleLee** [comment]
I think this is maybe just #15 again...

**Comment by ImpleLee** [comment]
In rockspec of 1.0.1, the tag is specified as `v1.0.0`, so users from `luarocks` will just use the wrong code...
https://github.com/andremm/lua-parser/blob/e98c1f4fb8e9041effb8b6e7e3025bf5d06fdc9e/rockspecs/lua-parser-1.0.1-1.rockspec#L6

**Comment by andremm** [comment]
> 5\. ./bin/lua parse.lua "for i=1, 10 do print(i)"

Thanks for spotting this issue and sorry for the inconvenience. I just pushed a new release that should solved this issue.
