### ISSUE TITLE
[Proposal] Unify tags 'True' and 'False' into 'Boolean'

### ISSUE THREAD

**Issue by alexeyknyshev** [andremm/lua-parser#5]
I think using table representation for booleans like this:
```lua
{
    false,
    tag = 'Boolean',
}
```
will be more conforming with lua type system and other tags, such as **Number** or **String**

**Comment by alexeyknyshev** [comment]
Friendly reminder

**Comment by andremm** [comment]
Makes sense, I will take a look at it. Sorry, for taking some time to reply.

**Comment by andremm** [comment]
I just pushed a commit that implements your request.

**Comment by alexeyknyshev** [comment]
Thanks!
