### ISSUE TITLE
<= and >= are scanned as the same token

### ISSUE THREAD

**Issue by forflo** [andremm/lua-parser#6]
Your example produces the same syntax tree for two very different code snippets

    a=1>=4
    a=1<=4

Bot produce

    { `Set{ { `Id "a" }, { `Op{ "le", `Number "1", `Number "4" } } } }

**Comment by andremm** [comment]
Actually, they do not produce the same AST, as the parser reproduces the same behavior that is expressed by the Lua manual: **A comparison a > b is translated to b < a and a >= b is translated to b <= a**.

That is, the example `a=1<=4` produces the following AST:
`{ Set{ { Id "a" }, { Op{ "le", Number "1", Number "4" } } } }`
which has the operation `1 <= 4`.

Please, note that the example `a=1>=4` generates the following AST:
`{ Set{ { Id "a" }, { Op{ "le", Number "4", Number "1" } } } }`
which has the operation `4 <= 1` and is different from the above AST.

**Comment by forflo** [comment]
Ah, thanks for the clarification. sorry that I didn't recheck the order of the operands.
